FROM gradle:jdk17-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME
ARG STORAGE_TOKEN
ARG STORAGE_KEY
ARG STORAGE_SECRET
ARG API_AUTH_ADMIN_URL
ARG API_PAYMENT_URL
ARG API_STORAGE_URL

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}
ENV STORAGE_TOKEN ${STORAGE_TOKEN}
ENV STORAGE_KEY ${STORAGE_KEY}
ENV STORAGE_SECRET ${STORAGE_SECRET}
ENV API_AUTH_ADMIN_URL ${API_AUTH_ADMIN_URL}
ENV API_PAYMENT_URL ${API_PAYMENT_URL}
ENV API_STORAGE_URL ${API_STORAGE_URL}

WORKDIR /app
COPY ./build/libs/games-apps-store-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java","-jar","games-apps-store-0.0.1-SNAPSHOT.jar"]
